version: '3'
services:
  odoo:
    image: odoo:17.0
    ports:
      - "8070:8069"
    volumes:
      - ./chatbot_modules:/mnt/extra-addons
    environment:
      - HOST=localhost
      - ADMIN_PASSWORD=admin
